spring.application.name=project

server.port = 9999

#mysql 접근 관련
spring.datasource.url = jdbc:mysql://localhost:3306/mydb
spring.datasource.username = myuser
spring.datasource.password = 1234

#dbcp 최대 20
spring.datasource.hikari.maximum-pool-size = 20

#dbcp 최소 10개 유지
spring.datasource.hikari.minimum-idle = 20

#mybatis의 mapper파일
mybatis.mapper-locations = classpath:mapper/**/*.xml

#vo에 별칭 추가
mybatis.type-aliases-package = com.kh.project.vo

#jstl 경로
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
